conky.config = {
    alignment = 'top_left',
    gap_x = 20,
    gap_y = 40,

    background = true,
    double_buffer = true,
    update_interval = 1,

    cpu_avg_samples = 2,
    net_avg_samples = 2,

    override_utf8_locale = true,

    use_xft = true,
    font = 'JetBrains Mono:size=11',

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,

    default_color = 'white',

    own_window = true,
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    minimum_width = 360,
    maximum_width = 360,
};

conky.text = [[
${font JetBrains Mono:size=26}${time %H:%M}${font}
${time %A, %d %B %Y}

${font JetBrains Mono:bold:size=12}SYSTEM${font}

${font JetBrains Mono:bold:size=12}CPU${font}   ${cpu}%
${cpugraph cpu0 45,260 00FFFF FF00FF}

${font JetBrains Mono:bold:size=12}CPU CORES${font}
Core1 ${cpu cpu1}% ${cpubar cpu1 6,120}
Core2 ${cpu cpu2}% ${cpubar cpu2 6,120}
Core3 ${cpu cpu3}% ${cpubar cpu3 6,120}
Core4 ${cpu cpu4}% ${cpubar cpu4 6,120}

${font JetBrains Mono:bold:size=12}TEMP${font}    ${execi 5 sensors | grep -m 1 'Package' | awk '{print $4}'}

${font JetBrains Mono:bold:size=12}RAM${font}     $mem / $memmax
${memgraph 45,260 00FFFF FF00FF}

${font JetBrains Mono:bold:size=12}DISK${font}    ${fs_used /} / ${fs_size /}
${diskiograph 45,260 / 00FFFF}

${font JetBrains Mono:bold:size=12}FAN${font}     ${execi 2 sensors | grep fan1 | awk '{print $2}'} RPM

${font JetBrains Mono:bold:size=12}UPTIME${font}  ${uptime}
]];
